### ISSUE TITLE
Erro para Iniciar via o cliente

### ISSUE THREAD

**Issue by andersondeoliveiramachado** [AlanMartines/mywhats-api-node#1]
@AlanMartines No server quando recebe o POST do cliente , acontece esse erro :

![image](https://user-images.githubusercontent.com/1152426/102575056-10417580-40d1-11eb-89a4-e3645b939ef7.png)

![image](https://user-images.githubusercontent.com/1152426/102575083-23544580-40d1-11eb-8820-8c918a64632a.png)

![image](https://user-images.githubusercontent.com/1152426/102614247-a5b12980-4112-11eb-9ffb-c78feae51597.png)

![image](https://user-images.githubusercontent.com/1152426/102614416-f032a600-4112-11eb-9595-9c3e40c6a106.png)

Coloquei uma chamada get routes\sistem.routes.js , e inicia normalmente.

``router.get("/Start", async (req, res, next) => {
    //
    //http://localhost:9000/sistem/Start?SessionName=e961578c-1a3a-4b99-a1d3-745e4bcbc217``

**Comment by AlanMartines** [comment]
Opa vlw vou analisar e efetuar a correção...

**Comment by AlanMartines** [comment]
Fiz alguns testes, e não apresentou problemas...

**Comment by ricardorodh** [comment]
Oi boa tarde.
Primeiramente, parabéns pelo projeto.
Estou com esse mesmo problema no body-parser. Já tentei de tudo, mudei versão do node, atual usando a 14x, mas tentei a 10x e não resolveu.
Será que é minha máquina? uso o Ubuntu 20.04.1 LTS 64bits
Algo que eu possa fazer pra resolver?
abraço.

**Comment by AlanMartines** [comment]
Qual programa vocês estão usando para fazer os testes, o Insomnia ou Postman..., e para start da API necessário passar um nome para o SessionName via post...
