### ISSUE TITLE
nada acontece tanto no start como no QRcode

### ISSUE THREAD

**Issue by Mellosre** [AlanMartines/mywhats-api-node#2]
![2](https://user-images.githubusercontent.com/35300051/104777411-5fbfa380-575a-11eb-9943-b8338f8fb238.PNG)
![1](https://user-images.githubusercontent.com/35300051/104777482-7c5bdb80-575a-11eb-98cf-84dce3011de5.PNG)

não consigo fazer funcionar não carrega o qrcode e nada aparece na porta 9000

![3](https://user-images.githubusercontent.com/35300051/104777589-ab724d00-575a-11eb-9bf5-ca3b03a31d58.PNG)

**Comment by AlanMartines** [comment]
A API usa método POST para consumir os recursos...

**Comment by Mellosre** [comment]
http://localhost:9000/start?sessionName=session1

nada acontece

http://localhost:9000/qrcode?sessionName=session1&image=true

Nada

**Comment by AlanMartines** [comment]
Importa esse template no insomnia para você fazer os teste... E a API usa o método POST... 

https://www.github.com/AlanMartines/mywhats-api-node/tree/main/Insomnia_2021-01-14.json

**Comment by Mellosre** [comment]
Boa noite ALAN 

Mesma coisa o mais engraçado que com o myzap eu consigo rodar de boa!

Enviado via iPhone

**Comment by AlanMartines** [comment]
Me manda um email com com seu WhatsApp

alancpmartines@hotmail.com
