### ISSUE TITLE
body-parser error

### ISSUE THREAD

**Issue by ricardorodh** [AlanMartines/mywhats-api-node#3]
Oi boa tarde.
Primeiramente, parabéns pelo projeto.
Estou com esse mesmo problema no body-parser, que já tem aqui nos Issues.
Já tentei de tudo, mudei versão do node, atual usando a 14x, mas tentei a 10x e não resolveu.
Será que é minha máquina? uso o Ubuntu 20.04.1 LTS 64bits
Algo que eu possa fazer pra resolver?
abraço.

**Comment by AlanMartines** [comment]
Qual programa você está usando para fazer os testes, o Insomnia ou Postman...
