### ISSUE TITLE
Como fazer um post de imagem

### ISSUE THREAD

**Issue by devpremium** [AlanMartines/mywhats-api-node#4]
![image](https://user-images.githubusercontent.com/52453013/108424728-4e196200-7218-11eb-9dcf-a526d7db38c6.png)
Como fazer um post de imagem nesta função, estou com erro de undefined no buffer.toString('base64'), mas acredito que estou fazendo algo errado no post

**Comment by AlanMartines** [comment]
De que forma você esta fazendo o envio, qual programa esta usando para os teste, Postman ou Insomnia?

**Comment by devpremium** [comment]
![image](https://user-images.githubusercontent.com/52453013/108599840-453ca380-7372-11eb-995c-fa7b349c58fc.png)
Estou usando o postman, ai esta a forma que estou enviando

**Comment by AlanMartines** [comment]
Usa a opção x-www-form...

**Comment by devpremium** [comment]
![image](https://user-images.githubusercontent.com/52453013/108601982-5ee3e800-737e-11eb-9b1a-f8c945df720d.png)
Eu fiz essa alteração e funcionou, no modo x-www-form-urlencoded não é possivel selecionar arquivo

**Comment by AlanMartines** [comment]
Usa o Insomnia e usa essa template

https://www.github.com/AlanMartines/mywhats-api-node/tree/main/Insomnia_2021-01-14.json
