### ISSUE TITLE
checkNumberStatus Error

### ISSUE THREAD

**Issue by guilhermehduarte** [AlanMartines/mywhats-api-node#5]
The checkNumberStatus method has stopped validating.

The return is 200, however, only the searched number appears on the return:

```
//response to sistem/checkNumberStatus 
{
    "Number": 5512997709337
}
```

**Comment by AlanMartines** [comment]
Estarei verificando... Obrigado por informar...

**Comment by AlanMartines** [comment]
Fiz uns teste e função esta funcionando...
