### ISSUE TITLE
Salvar sessão para próximo acesso

### ISSUE THREAD

**Issue by ricardorodh** [AlanMartines/mywhats-api-node#6]
Boa tarde gente fina.
Estou tentando salvar a sessão para o próximo acesso, mas não estou conseguindo nessa versão mais nova do venom, não aparece nada na pasta token que setei nas configurações.

`folderNameToken: "tokens"`

`const browserSessionToken = client.getSessionTokenBrowser();`

Teria como colocar junto ao código essa funcionalidade?

**Comment by AlanMartines** [comment]
Como assim próxima sessão... Seria na situação de depois de ter encerrado o processo inicial e depois executar novamente ele não precisa ler o qr code novamente? Seria isso...?

**Comment by ricardorodh** [comment]
Sim, coloquei em uma variável, para tenta salvar em um arquivo como fazia o venom antes .
Como faço para guardar os dados e quando excecutar navamente, não precisar ler o qrcode.

`
    // BrowserSessionToken
    // To receive the client's token use the function await clinet.getSessionTokenBrowser()
    {
      WABrowserId: '"UnXjH....."',
      WASecretBundle:
        '{"key":"+i/nRgWJ....","encKey":"kGdMR5t....","macKey":"+i/nRgW...."}',
      WAToken1: '"0i8...."',
      WAToken2: '"1@lPpzwC...."',
    }
`

**Comment by AlanMartines** [comment]
Fiz uns teste e a API está criando o arquivo normalmente...

**Comment by ricardorodh** [comment]
Vi que adicionou **Salvar token do venom na nuvem** 
Ficou perfeito!!!
Parabéns
