### ISSUE TITLE
Verficar se a mensagem foi visualizada pelo usuario

### ISSUE THREAD

**Issue by devpremium** [AlanMartines/mywhats-api-node#7]
Sabe me dizer se possui alguma função para verficar se a mensagem foi visualizada pelo usuario que recebeu a mensagem da api

**Comment by AlanMartines** [comment]
Vou verificar se tem esse recurso no venon, caso tenha implemento....

**Comment by AlanMartines** [comment]
Acho que você procura seria isso

https://github.com/orkestral/venom#events

**Comment by devpremium** [comment]
Isso mesmo deu certo! Valeuu
